module.exports = {
	"say": 					/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" say "(.*)"/gmi,
	"kill": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" \[(.*) (.*) (.*)\] killed "(.*)<(\d*)><(.*)><(.*)>" \[(.*) (.*) (.*)\] with "(.*)"/gmi,
	"kill-h": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" \[(.*) (.*) (.*)\] killed "(.*)<(\d*)><(.*)><(.*)>" \[(.*) (.*) (.*)\] with "(.*)" \((.*)\)/gmi,
	"kill-o": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" \[(.*) (.*) (.*)\] killed other "(.*)<(\d*)>" \[(.*) (.*) (.*)\] with "(.*)"/gmi,
	"assist": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" assisted killing "(.*)<(\d*)><(.*)><(.*)>"/gmi,
	"nade": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" threw (.*) \[(.*) (.*) (.*)\]/gmi,
	"projectile":			/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): (.*) projectile spawned at (.*) (.*) (.*), velocity (.*) (.*) (.*)/gmi,
	"purchase": 			/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" purchased "(.*)"/gmi,
	"convar": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)" = "(.*)"/gmi,
	"matchvar": 			/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): server_cvar: "(.*)" "(.*)"/gmi,
	"player": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" triggered "(.*)"/gmi,
	"player_teamchange": 	/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)>" switched from team <(.*)> to <(.*)>/gmi,
	"team": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): Team "(.*)" triggered "(.*)" \(CT "(\d*)"\) \(T "(\d*)"\)"/gmi,
	"team_name": 			/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): Team playing "(.*)": (.*)/gmi,
	"score": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): Team "(.*)" scored "(\d*)" with "(\d*)" players/gmi,
	"world": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): World triggered "(.*)"/gmi,
	"connect": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" connected, address "(.*)"/gmi,
	"entered": 				/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" entered the game/gmi,
	"validated": 			/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" STEAM USERID validated/gmi,
	"disconnect": 			/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): "(.*)<(\d*)><(.*)><(.*)>" disconnected \((.*)\)/gmi,
	"map_loading": 			/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): Loading map "(.*)"/gmi,
	"map_started": 			/L (\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): Started map "(.*)" \(CRC "(.*)"\)/gmi
} 